ASP.Server/Models/ErrorViewModel.cs
using System;

namespace ASP.Server.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

ASP.Server/Controllers/BookController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ASP.Server.Database;
using ASP.Server.Model;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;

namespace ASP.Server.Controllers
{
    public class CreateBookModel
    {
        [Required]
        [Display(Name = "Nom")]
        public String Name { get; set; }

        // Ajouter ici tous les champ que l'utilisateur devra remplir pour ajouter un livre
        public String Author { get; set; }
        public Double Price { get; set; }
        public String Content { get; set; }

        // Liste des genres séléctionné par l'utilisateur
        public List<int> Genres { get; set; }

        // Liste des genres a afficher à l'utilisateur
        public IEnumerable<Genre> AllGenres { get; init;  }
    }

    public class BookController : Controller
    {
        private readonly LibraryDbContext libraryDbContext;

        public BookController(LibraryDbContext libraryDbContext)
        {
            this.libraryDbContext = libraryDbContext;
        }
        public ActionResult<IEnumerable<Book>> List()
        {
            // récupérer les livres dans la base de donées pour qu'elle puisse être affiché
            List<Book> ListBooks = null;

            if (libraryDbContext.Books.ToList() != null)
                ListBooks = libraryDbContext.Books.Include(book => book.Genres).ToList();

            return View(ListBooks);
        }

        public ActionResult<CreateBookModel> Create(CreateBookModel book)
        {
            // Le IsValid est True uniquement si tous les champs de CreateBookModel marqués Required sont remplis
            if (ModelState.IsValid)
            {
                // Il faut intéroger la base pour récupérer l'ensemble des objets genre qui correspond aux id dans CreateBookModel.Genres
                List<Genre> genres = libraryDbContext.Genre.Where(genre => book.Genres.Contains(genre.Id)).ToList();
                // Completer la création du livre avec toute les information nécéssaire que vous aurez ajoutez, et metter la liste des gener récupéré de la base aussi
                libraryDbContext.Add(new Book() { Name = book.Name, Author = book.Author, Price = book.Price, Content = book.Content, Genres = genres});
                libraryDbContext.SaveChanges();
            }

            // Il faut interoger la base pour récupérer tous les genres, pour que l'utilisateur puisse les slécétionné
            return View(new CreateBookModel() { AllGenres = libraryDbContext.Genre.ToList() } );
        }

        
        public ActionResult Delete(int id)
        {
                libraryDbContext.Remove(libraryDbContext.Find<Book>(id));
                libraryDbContext.SaveChanges();

                return Ok();

        }
    }
}

ASP.Server/Controllers/GenreController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ASP.Server.Database;
using ASP.Server.Model;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.ComponentModel.DataAnnotations;

namespace ASP.Server.Controllers
{
    public class CreateGenreModel
    {
        [Required]
        [Display(Name = "Nom")]
        public String Name { get; set; }
    }

    public class GenreController : Controller
    {
        private readonly LibraryDbContext libraryDbContext;

        public GenreController(LibraryDbContext libraryDbContext)
        {
            this.libraryDbContext = libraryDbContext;
        }

        // A vous de faire comme BookController.List mais pour les genres !
        public ActionResult<IEnumerable<Genre>> List()
        {
            List<Genre> ListGenres=null;
            // récupérer les livres dans la base de donées pour qu'elle puisse être affiché
            if (libraryDbContext.Genre.ToList() != null)
            {
                 ListGenres = libraryDbContext.Genre.Include(g=> g.Books).ToList();
            }else
            {
                throw new Exception();
            }
            return View(ListGenres);
        }

        public ActionResult<CreateGenreModel> Create(CreateGenreModel genre)
        {
            // Le IsValid est True uniquement si tous les champs de CreateGenreModel marqués Required sont remplis
            if (ModelState.IsValid)
            {
                libraryDbContext.Add(new Genre() {Name=genre.Name});
                libraryDbContext.SaveChanges();
            }
            return View(new CreateGenreModel() {});
        }
    }
}

ASP.Server/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using ASP.Server.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace ASP.Server.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

ASP.Server/Views/Book/Create.cshtml
@using ASP.Server.Controllers
@model CreateBookModel
@{
    ViewData["Title"] = "Add a book";
}
<style>
.input-group {
    margin-top:80px;
    display:flex;
    justify-content:space-between;
    flex-wrap:wrap;
}
input, textarea, select {
    flex-basis:85%;
}
label {

    flex-basis:10%;
}
</style>

<!-- Voici une facon de faire, mais ce n'est pas la seul, a vous de jouer ! -->
<form asp-controller="Book" asp-action="Create">
    <div class="input-group">
        <label asp-for="Name"></label>
        <input asp-for="Name" />
    </div>
    <div class="input-group">
        <label asp-for="Author"></label>
        <input asp-for="Author" />
    </div>
    <div class="input-group">
        <label type="number" asp-for="Price"></label>
        <input asp-for="Price" />
    </div>
    <div class="input-group">
        <label asp-for="Content"></label>
        <input asp-for="Content" />
    </div>
    <div class="input-group">
        <label asp-for="Genres"></label>
        <!--Si la page rend une erreur a cette ligne, c'est que vous n'avez pas envoyé la liste des genres dans le Controller !!! ! -->
        <select asp-for="Genres" asp-items="@(new SelectList(Model.AllGenres,"Id","Name"))">
        </select>
    </div>
    <input type="submit" value="Add" style="width: 100%; margin-top: 50px" />
</form>

ASP.Server/Views/Book/List.cshtml
@using ASP.Server.Model
@model IEnumerable<Book>

@{
    ViewData["Title"] = "Home Page";
}

<div class="listeBooks">
    <h1>List Books:</h1>
    <!-- la liste des genres est dans la variable Model qui est typé en ligne 3, elle correspond à la variable xxx dans View(xxx) du controller -->
    @foreach (var book in Model)
    {
        <div style = "margin-top:50px; margin-bottom: 10px">
        <table style = "border-collapse: collapse; margin-top:100px;margin-bottom: 5px; display: inline"> 

            <tr><td style = "border: 1px solid black">Nom auteur</td><td style ="border: 1px solid black">@book.Author</td></tr>
             <tr><td style ="border: 1px solid black">Nom Livre</td><td style ="border: 1px solid black">@book.Name</td></tr>
             <tr><td style ="border: 1px solid black">Prix</td><td style ="border: 1px solid black">@book.Price</td></tr>
             <tr><td style ="border: 1px solid black">Contenu</td><td style ="border: 1px solid black">@book.Content</td></tr>
             <tr><td style ="border: 1px solid black">Genre</td><td style ="border: 1px solid black">@foreach(var genre in book.Genres){<div>@genre.Name</div> }</td></tr>

        </table>

       <button type="button"  title="employs" style="width: 100px; margin-right: 5px; position: relative;top: 40px"  onclick="DoComfirm()" return false>Delete</button>
        <script type="text/javascript">
          function DoComfirm()
            {
                  window.location.href = '@Url.Action("Delete", "Book", new { id = @book.Id})';
                  if (confirm('@book.Name is removed')) {
                    window.location.href = '@Url.Action("List", "Book")';
                  }
            }
        </script>
        <input type="submit" value="Modify" style="width: 100px; margin-right: 5px; position: relative;top: 40px" /></div>
    }    
</div>

ASP.Server/Views/Genre/Create.cshtml
@using ASP.Server.Controllers
@model CreateGenreModel
@{
    ViewData["Title"] = "Add a genre";
}
<style>
.input-group {
    margin-top:30px;
    display:flex;
    justify-content:space-between;
    flex-wrap:wrap;
}
input, textarea, select {
    flex-basis:85%;
}
label {
    margin-top: 150px;
    flex-basis:10%;
}

</style>

<!-- Voici une facon de faire, mais ce n'est pas la seul, a vous de jouer ! -->
<form asp-controller="Genre" asp-action="Create">
    <label for="Name">Nom du genre:</label>
    <input type="text" name="Name" id="Name" style="width: 100%; margin-top: 50px" />
    <input type="submit" value="Add" style="width: 100%; margin-top: 50px" />
</form>

ASP.Server/Views/Genre/List.cshtml
@using ASP.Server.Model

@model IEnumerable<Genre>
@{
    ViewData["Title"] = "Liste Type";
}

<div class="listType">
    <h1>List Type:</h1>
    <!-- la liste des genres est dans la variable Model qui est typé en ligne 3, elle correspond à la variable xxx dans View(xxx) du controller -->
    @foreach (var genre in Model)
    {



        <div style = "margin-bottom: 10px; margin-top:50px;">
        <table style = "border-collapse: collapse; margin-bottom: 5px; display: inline"> 

            <tr><td style = "border: 1px solid black">id</td><td style ="border: 1px solid black">@genre.Id</td></tr>
             <tr><td style ="border: 1px solid black">Genre Livre</td><td style ="border: 1px solid black">@genre.Name</td></tr>
          
        </table></div>



    }
</>

ASP.Server/Views/Home/Index.cshtml
@{
ViewData["Title"] = "Home Page";
}



<header class="masthead text-black text-center">
<div class="container d-flex align-items-center flex-column">
<!-- Masthead Avatar Image-->
<img class="masthead-avatar mb-5" src="assets/img/livre.png" alt="" />
<!-- Masthead Heading-->
<h1 class="masthead-heading text-uppercase mb-0">Bibliotheque</h1>
<!-- Icon Divider-->
<div class="divider-custom divider-light">
<div class="divider-custom-line"></div>
<div class="divider-custom-icon"><i class="fas fa-star"></i></div>
<div class="divider-custom-line"></div>
</div>
<!-- Masthead Subheading-->
<p class="masthead-subheading font-weight-light mb-0">Welcome to your library!</p>
</div>
</header>

ASP.Server/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utfcolorname="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - APP</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>

    <header>
<nav class="navbar navbar-expand-lg bg-secondary text-uppercase fixed-top" id="mainNav">
<div class="container">
<a class="navbar-brand" js-scroll-trigger asp-area="" asp-controller="Home" asp-action="Index">Home</a>
<button class="navbar-toggler navbar-toggler-right text-uppercase font-weight-bold bg-primary text-white rounded" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
Menu
<i class="fas fa-bars"></i>
</button>
<div class="collapse navbar-collapse" id="navbarResponsive">
<ul class="navbar-nav ml-auto">
<li class="nav-item" mx-0 mx-lg-1>
<a class="nav-link text-dark  py-3 px-0 px-lg-3 rounded js-scroll-trigger " asp-area="" asp-controller="Book" asp-action="List">Books</a>
</li>
<li class="nav-item" mx-0 mx-lg-1>
<a class="nav-link text-dark py-3 px-0 px-lg-3 rounded js-scroll-trigger" asp-area="" asp-controller="Genre" asp-action="List">Types</a>
</li>
<li class="nav-item" mx-0 mx-lg-1>
<a class="nav-link text-dark py-3 px-0 px-lg-3 rounded js-scroll-trigger" asp-area="" asp-controller="Book" asp-action="Create">Add book</a>
</li>
<li class="nav-item" mx-0 mx-lg-1>
<a class="nav-link text-dark py-3 px-0 px-lg-3 rounded js-scroll-trigger" asp-area="" asp-controller="Genre" asp-action="Create">Add type</a>
</li>
</ul>
</div>
</div>
</nav>
</header>
  
        
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - APP - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>